GAMEPLAY_COLUMNS = [
    "userid",
    "childid",
    "sessionid",
    "local_eventdate",
    "local_timestamp",
    "local_startdate",
    "gausercountry",
    "clientversion",
    "pnsmode",
    "pnsword",
    "pnsduration",
    "pnsmistakes",
    "exposures",
    "day_since_start",
]

MINIMUM_GAMEPLAY_COLUMNS = [
    "userid",
    "childid",
    "eventname",
    "eventtimestamp",
    "mssincelastevent",
    "timezoneoffset",
    "gausercountry",
    "clientversion",
    "pnsmode",
    "pnsword",
    "pnsduration",
    "pnsmistakes",
]

FULL_WORD_INFO_COLS = [
    "word",
    "word_id",
    "word_grade",
    "age_of_acq",
    "pos",
    "syllables",
    "web_freq",
    "news_freq",
    "gen_freq",
    "fict_freq",
    "wiki_freq",
    "web_rank",
    "news_rank",
    "fiction_rank",
    "general_rank",
    "wiki_rank",
    "lexile",
]

KEEP_COLS_PT = [
    "userid",
    "childid",
    "local_eventdate",
    "local_timestamp",
    "local_startdate",
    "gausercountry",
    "clientversion",
    "pnsmode",
    "pnsword",
    "pnsduration",
    "pnsmistakes",
    "exposures",
    "day_since_start",
    "minutes_played",
]
